name: Build Pipeline

# Runs on push to master
on:
  push:
    branches:
      - master

jobs:
  test:
    # if the commit message doesnt contain [skip-ci] then run this job
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/tests/requirements.txt -r src/master/requirements.txt -r src/slave/requirements.txt
          
      - name: Run unit tests
        working-directory: ./src
        run: coverage run -m pytest
        
      - name: Generate Slave Coverage Reports
        working-directory: ./src
        run: coverage xml -o coverage.xml

      - name: Upload Slave Test Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          # Path to coverage file to upload
          file: src/coverage.xml
          # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
          flags: unittests
          # Specify whether or not CI build should fail if Codecov runs into an error during upload
          fail_ci_if_error: true
