name: PR Pipeline

# Runs on PRs to master
on:
  pull_request:
    branches:
      - master

jobs:
  Tests:
    # if the commit message doesnt contain [skip-ci] then run this job
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    name: Pylint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint \
        -r src/tests/requirements.txt \
        -r src/master/requirements.txt \
        -r src/slave/requirements.txt

    - name: Lint with pylint
      run: pylint --rcfile=pylintrc src/*/*.py
        
    - name: Run unit tests
      run: pytest
