name: PR Pipeline

# Runs on PRs to master
on:
  pull_request:
    branches:
      - master

jobs:
  python-linting:
    # if the commit message doesnt contain [skip-ci] then run this job
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    name: Pylint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint \
        -r src/master/requirements.txt \
        -r src/slave/requirements.txt

    - name: Lint with pylint
      run: |
        pylint --rcfile=pylintrc src/*/*.py

  test:
    # if the commit message doesnt contain [skip-ci] then run this job
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Master unit tests
        run: docker build -f "master.Dockerfile" -t master/unit_tests --target test-env .

      - name: Run Slave unit tests
        run: docker build -f "slave.Dockerfile" -t slave/unit_tests --target test-env .
